<?php

namespace AppBundle\Repository;

/**
 * SectorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorsRepository extends \Doctrine\ORM\EntityRepository
{
}
